version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:10" # 8h10 en france
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 1
    target-branch: "V2"
    groups:
      all-dependencies:
        patterns:
          - "*"
