name: Dependabot Auto Merge

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Assurez-vous d'utiliser la version Node.js appropriée pour votre projet

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

          
      - name: auto-dependabot-pull-request-merge
        # You may pin to the exact commit or the version.
        # uses: KeisukeYamashita/auto-dependabot-pull-request-merge@a7ac708f2c3b0c28e86ad099d6ce7f2a5219fd94
        uses: KeisukeYamashita/auto-dependabot-pull-request-merge@v1
        with:
          token: ${{ secrets.DOCS_SECRETS }}
