name: Dependabot Auto Merge

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Assurez-vous d'utiliser la version Node.js appropriée pour votre projet

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Get Pull Request ID
        id: get_pr_id
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            return pr ? pr.number : null;

      - name: Auto merge Dependabot PR
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          pull-request-number: ${{ steps.get_pr_id.outputs.result }}
          merge-method: merge
