name: Build Image Preprod

on:
  push:
      branches:
      - preprod

jobs:
  Build-Images:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Registery
        uses: docker/login-action@v3
        with:
          registry: registry.as216117.net:9443
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: registry.as216117.net:9443/docsclientxcms:preprod

      - name: Restart docker-compose via ssh
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          user: ${{ secrets.VPS_USER }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          command: /var/www/preprod.docs.clientxcms.com/restart-docker.sh
